-- CREATE TYPE "public"."skilltype" AS ENUM('LP', 'R', 'BD', 'Q', 'COM', 'CRI', 'NTA');--> statement-breakpoint
-- CREATE TABLE "accounts" (
-- 	"id" text PRIMARY KEY NOT NULL,
-- 	"account_id" text NOT NULL,
-- 	"provider_id" text NOT NULL,
-- 	"user_id" text NOT NULL,
-- 	"access_token" text,
-- 	"refresh_token" text,
-- 	"id_token" text,
-- 	"access_token_expires_at" timestamp,
-- 	"refresh_token_expires_at" timestamp,
-- 	"scope" text,
-- 	"password" text,
-- 	"created_at" timestamp NOT NULL,
-- 	"updated_at" timestamp NOT NULL
-- );
--> statement-breakpoint
-- CREATE TABLE "sessions" (
-- 	"id" text PRIMARY KEY NOT NULL,
-- 	"expires_at" timestamp NOT NULL,
-- 	"token" text NOT NULL,
-- 	"created_at" timestamp NOT NULL,
-- 	"updated_at" timestamp NOT NULL,
-- 	"ip_address" text,
-- 	"user_agent" text,
-- 	"user_id" text NOT NULL,
-- 	"impersonated_by" text,
-- 	CONSTRAINT "sessions_token_unique" UNIQUE("token")
-- );
--> statement-breakpoint
-- CREATE TABLE "users" (
-- 	"id" text PRIMARY KEY NOT NULL,
-- 	"name" text NOT NULL,
-- 	"email" text NOT NULL,
-- 	"email_verified" boolean NOT NULL,
-- 	"image" text,
-- 	"created_at" timestamp NOT NULL,
-- 	"updated_at" timestamp NOT NULL,
-- 	"role" text,
-- 	"banned" boolean,
-- 	"ban_reason" text,
-- 	"ban_expires" timestamp,
-- 	CONSTRAINT "users_email_unique" UNIQUE("email")
-- );
--> statement-breakpoint
-- CREATE TABLE "verifications" (
-- 	"id" text PRIMARY KEY NOT NULL,
-- 	"identifier" text NOT NULL,
-- 	"value" text NOT NULL,
-- 	"expires_at" timestamp NOT NULL,
-- 	"created_at" timestamp,
-- 	"updated_at" timestamp
-- );
--> statement-breakpoint
-- CREATE TABLE "caregivers" (
-- 	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
-- 	"name" text NOT NULL,
-- 	"user_id" text NOT NULL
-- );
--> statement-breakpoint
-- CREATE TABLE "specialtimes" (
-- 	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
-- 	"completed" boolean DEFAULT false NOT NULL,
-- 	"created_at" timestamp DEFAULT now() NOT NULL,
-- 	"updated_at" timestamp DEFAULT now() NOT NULL,
-- 	"toys" text,
-- 	"praise" integer DEFAULT 0 NOT NULL,
-- 	"reflect" integer DEFAULT 0 NOT NULL,
-- 	"describe" integer DEFAULT 0 NOT NULL,
-- 	"question" integer DEFAULT 0 NOT NULL,
-- 	"command" integer DEFAULT 0 NOT NULL,
-- 	"criticism" integer DEFAULT 0 NOT NULL,
-- 	"negative_talk" integer DEFAULT 0 NOT NULL,
-- 	"duration" real DEFAULT 0 NOT NULL,
-- 	"caregiversid" uuid NOT NULL
-- );
--> statement-breakpoint
-- CREATE TABLE "utterances" (
-- 	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
-- 	"session_id" uuid NOT NULL,
-- 	"child_utterance" text,
-- 	"parent_utterance" text NOT NULL,
-- 	"skillcode" "skilltype" NOT NULL,
-- 	"created_at" timestamp DEFAULT now()
-- );
--> statement-breakpoint
CREATE TABLE "one_time_codes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"code" text NOT NULL,
	"user_id" text NOT NULL,
	"caregivers_id" uuid,
	"used" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
-- ALTER TABLE "accounts" ADD CONSTRAINT "accounts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
-- ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
-- ALTER TABLE "caregivers" ADD CONSTRAINT "caregivers_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
-- ALTER TABLE "specialtimes" ADD CONSTRAINT "specialtimes_caregiversid_caregivers_id_fk" FOREIGN KEY ("caregiversid") REFERENCES "public"."caregivers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
-- ALTER TABLE "utterances" ADD CONSTRAINT "utterances_session_id_specialtimes_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."specialtimes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "one_time_codes" ADD CONSTRAINT "one_time_codes_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "one_time_codes" ADD CONSTRAINT "one_time_codes_caregivers_id_caregivers_id_fk" FOREIGN KEY ("caregivers_id") REFERENCES "public"."caregivers"("id") ON DELETE cascade ON UPDATE no action;