services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: pcituser
      POSTGRES_PASSWORD: pcitpassword
      POSTGRES_DB: pcitdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    