import type { Metadata } from "next";
import "./globals.css";
// import "/Users/takadanana/Desktop/Startup/pcit-platform/styles/globals.css"
import { Header } from "@/components/header"
import type { ReactNode } from "react"
import { Providers } from "./providers"
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { SidebarWrapper } from "@/components/sidebar_wrapper"; // NEW

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
          <body className="font-sans antialiased bg-gray-50">
            <Providers>

                <Header />
                <div className="flex">
                  <main className="flex-1 p-6">
                    {children}

                  </main>
                </div>
            </Providers>
          </body>
        </html>
  );
}
