import type { Metadata } from "next";
import "./globals.css";
// import "/Users/takadanana/Desktop/Startup/pcit-platform/styles/globals.css"
import { Header } from "@/components/header"
import type { ReactNode } from "react"
import { Providers } from "./providers"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={"font-sans antialiased"}>
          <Header />
          {children}
        </body>
      </Providers>
    </html>
  );
}
